//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCVolunteerScheduler.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class EventsPerDayWithNumVolunteerEntities : DbContext
    {
        public EventsPerDayWithNumVolunteerEntities()
            : base("name=EventsPerDayWithNumVolunteerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        [EdmFunction("EventsPerDayWithNumVolunteerEntities", "GetEventsForDay")]
        public virtual IQueryable<GetEventsForDay_Result> GetEventsForDay(Nullable<System.DateTime> day)
        {
            var dayParameter = day.HasValue ?
                new ObjectParameter("Day", day) :
                new ObjectParameter("Day", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetEventsForDay_Result>("[EventsPerDayWithNumVolunteerEntities].[GetEventsForDay](@Day)", dayParameter);
        }
    }
}
