//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCVolunteerScheduler.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class EventSPEntities : DbContext
    {
        public EventSPEntities()
            : base("name=EventSPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual int Delete_Event(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delete_Event", iDParameter);
        }
    
        public virtual int Insert_Event(string event_Title, string event_Description, Nullable<System.DateTime> event_Date, Nullable<System.TimeSpan> start_Time, Nullable<System.TimeSpan> end_Time, Nullable<int> max_Volunteers)
        {
            var event_TitleParameter = event_Title != null ?
                new ObjectParameter("Event_Title", event_Title) :
                new ObjectParameter("Event_Title", typeof(string));
    
            var event_DescriptionParameter = event_Description != null ?
                new ObjectParameter("Event_Description", event_Description) :
                new ObjectParameter("Event_Description", typeof(string));
    
            var event_DateParameter = event_Date.HasValue ?
                new ObjectParameter("Event_Date", event_Date) :
                new ObjectParameter("Event_Date", typeof(System.DateTime));
    
            var start_TimeParameter = start_Time.HasValue ?
                new ObjectParameter("Start_Time", start_Time) :
                new ObjectParameter("Start_Time", typeof(System.TimeSpan));
    
            var end_TimeParameter = end_Time.HasValue ?
                new ObjectParameter("End_Time", end_Time) :
                new ObjectParameter("End_Time", typeof(System.TimeSpan));
    
            var max_VolunteersParameter = max_Volunteers.HasValue ?
                new ObjectParameter("Max_Volunteers", max_Volunteers) :
                new ObjectParameter("Max_Volunteers", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Insert_Event", event_TitleParameter, event_DescriptionParameter, event_DateParameter, start_TimeParameter, end_TimeParameter, max_VolunteersParameter);
        }
    
        public virtual int Update_Event(Nullable<int> iD, string title, string description, Nullable<System.DateTime> date, Nullable<System.TimeSpan> start, Nullable<System.TimeSpan> end, Nullable<int> max_Volunteers)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var titleParameter = title != null ?
                new ObjectParameter("Title", title) :
                new ObjectParameter("Title", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            var dateParameter = date.HasValue ?
                new ObjectParameter("Date", date) :
                new ObjectParameter("Date", typeof(System.DateTime));
    
            var startParameter = start.HasValue ?
                new ObjectParameter("Start", start) :
                new ObjectParameter("Start", typeof(System.TimeSpan));
    
            var endParameter = end.HasValue ?
                new ObjectParameter("End", end) :
                new ObjectParameter("End", typeof(System.TimeSpan));
    
            var max_VolunteersParameter = max_Volunteers.HasValue ?
                new ObjectParameter("Max_Volunteers", max_Volunteers) :
                new ObjectParameter("Max_Volunteers", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Update_Event", iDParameter, titleParameter, descriptionParameter, dateParameter, startParameter, endParameter, max_VolunteersParameter);
        }
    }
}
