
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CCVolunteerScheduler.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Event
{

    public int Event_ID { get; set; }

    public string Event_Title { get; set; }

    public string Event_Description { get; set; }

    public System.DateTime Event_Date { get; set; }

    public System.TimeSpan Start_Time { get; set; }

    public System.TimeSpan End_Time { get; set; }

}

}
