//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCVolunteerScheduler.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class ToggleAutoRemindAction : DbContext
    {
        public ToggleAutoRemindAction()
            : base("name=ToggleAutoRemindAction")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual int ToggleAutoRemindOptOut(Nullable<long> volunteerID)
        {
            var volunteerIDParameter = volunteerID.HasValue ?
                new ObjectParameter("VolunteerID", volunteerID) :
                new ObjectParameter("VolunteerID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ToggleAutoRemindOptOut", volunteerIDParameter);
        }
    }
}
